name: Keiretsu Forum
favicon: null
layout_spectrum: 0.25746
typography_spectrum: 0.37937880237586796
title: K4SOCAL NEWS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#f6f6f6'
    - '#bdbdbd'
    - '#747474'
    - '#c92434'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
