name: Keiretsu Forum
favicon: null
layout_spectrum: 0.26288
typography_spectrum: 0.37937880237586796
title: News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c92434'
    - '#414141'
    - '#000000'
    - '#b8b8b8'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
