name: Keiretsu Forum
favicon: null
layout_spectrum: 0.25746
typography_spectrum: 0.37937880237586796
title: K4SOCAL NEWS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c0'
    - '#f2f2f2'
    - '#231f20'
    - '#c92434'
    - '#5d5e5f'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
