name: Keiretsu Forum
favicon: null
layout_spectrum: 0.67661
typography_spectrum: 0.37937880237586796
title: News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#f6f6f6'
    - '#bdbdbd'
    - '#747474'
    - '#c92434'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
