name: Keiretsu Forum
favicon: null
layout_spectrum: 0.64409
typography_spectrum: 0.37937880237586796
title: K4SOCAL NEWS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c0c0'
    - '#f2f2f2'
    - '#dbe0e3'
    - '#cfd4d7'
    - '#a4acaf'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
