name: Keiretsu Forum
favicon: null
layout_spectrum: 0.73804
typography_spectrum: 0.37937880237586796
title: News
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c92434'
    - '#414141'
    - '#000000'
    - '#b8b8b8'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
